### ISSUE TITLE
Doesn´t respawn after death

### ISSUE THREAD

**Issue by nahfe** [extendedmode/extendedmode#101]

**Comment by yagizher** [comment]
Be more clear. Title says nothing.

**Comment by smallo92** [comment]
You don't respawn by default with extendedmode, you need some other resource handling that. Such as esx_ambulancejob.

**Comment by NaominoDino** [comment]
@smallo92 is right! Download esx_ambulancejob ;)

**Comment by nahfe** [comment]
But if I don't want a job for that?

**Comment by yagizher** [comment]
I dont think its an option :D

**Comment by Walter-00** [comment]
> But if I don't want a job for that?

You could just make a resource that makes you re-spawn whenever you die, it shouldn't be very hard to do. For reference you should check out the esx_ambulancejob resource, that should give you more than enough insight to trigger a re-spawn whenever someone dies.

In-case you're not aware of where to find the ambulancejob resource, get it here: [https://github.com/extendedmode/esx_ambulancejob](url)
