### ISSUE TITLE
Negative Money after dead + using cash (FIX)

### ISSUE THREAD

**Issue by NaominoDino** [extendedmode/extendedmode#102]
Dear developers,

Can i join to your team please? I removed this lines cause es_extended or your extendedmode contains everything what you should call from essentilasmode :)

Here is the fix:
Remove this from /server/main.lua 

AddEventHandler("es:setMoney", function(user, value) ESX.GetPlayerFromId(user).setMoney(value, true) end)
AddEventHandler("es:addMoney", function(user, value) ESX.GetPlayerFromId(user).addMoney(value, true) end)
AddEventHandler("es:removeMoney", function(user, value) ESX.GetPlayerFromId(user).removeMoney(value, true) end)
AddEventHandler("es:set", function(user, key, value) ESX.GetPlayerFromId(user).set(key, value, true) end)

AddEventHandler("es_db:doesUserExist", function(identifier, cb)
	cb(true)
end)

**Comment by 0x346e3730** [comment]
You shouldn't run essentialmode and/or es_extended alongside extendedmode, those lines belong here, your installation is wrong most likely

**Comment by NaominoDino** [comment]
Dude, I use extendedmode with essentialmode for GCphone and other ESX jobs/mods. I installed it perfectly i think. :) But this was the problem at 4 servers :)

**Comment by 0x346e3730** [comment]
You need to remove `essentialmode` and `es_extended` folder from your `resources` folder.

**Comment by smallo92** [comment]
@GrosTon1 Can you not tell people to remove essentialmode. Essentialmode is supported to work with extendedmode, all @Naomi-Kali needed to do was update essentialmode to the newest version, not the newest released version, but just download the github repository.

**Comment by 0x346e3730** [comment]
my bad, I personally dont have it and it runs fine

**Comment by smallo92** [comment]
That's because it's optional, if people have essentialmode reliant resources they can run it. If not they don't. Simple.

**Comment by NaominoDino** [comment]
This is why i closed this issue section... @smallo92  :D haha
