### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by yagizher** [extendedmode/extendedmode#105]
I did install extendedmode correctly using this link: https://extendedmode.github.io/Using%20extendedmode/

But users can still use ADMIN COMMANDS.

**Comment by smallo92** [comment]
I said last time that you haven't set up Ace Permissions correctly. Please seek help on the FiveM discord or read the [FiveM Docs](https://docs.fivem.net/) to find out how Ace Permissions work. It's not an issue with extendedmode, it's just your inability to understand.

**Comment by yagizher** [comment]
I did install it how the extendedmode document said. I know its not an issue about extendedmode but i need help.

**Comment by smallo92** [comment]
You're not listening. ACE PERMISSIONS.
