### ISSUE TITLE
Commands issue

### ISSUE THREAD

**Issue by namikoglu** [extendedmode/extendedmode#108]
I just created my server and tried to use admin commands (while i was an user) and it worked. I tried them all and they worked too. I saw someone else's issue about it too but they just said ace permissions and idk how.

**Comment by yagizher** [comment]
Yes i have the same

**Comment by benzon** [comment]
if you added your self to your server.cfg that might be why :)

**Comment by namikoglu** [comment]
Nope. I didnt.

**Comment by NaominoDino** [comment]
Have you setted up perfectly your server.cfg? If you use extendedmode + essentialmode or only extendedmode it has to be work. Add yourself as admin inside the .cfg add.principal... Please read the setup part of the installation!

**Comment by namikoglu** [comment]
I think i saw the problem. I took a clear file, inserted my license key and still can use admin commands.

**Comment by daMairis** [comment]
Make sure to add in server.cfg:
add_principal group.admin group.user
add_ace resource.extendedmode command.add_ace allow
add_ace resource.extendedmode command.add_principal allow
add_ace resource.extendedmode command.remove_principal allow

**Comment by yagizher** [comment]
It was about my license key

**Comment by yagizher** [comment]
Try it, maybe it is about it too.
