### ISSUE TITLE
player dont spawn

### ISSUE THREAD

**Issue by iglesiiaskeviin** [extendedmode/extendedmode#109]
when entering the server, the character is not seen

**Comment by smallo92** [comment]
read the config it explains why

**Comment by iglesiiaskeviin** [comment]
I just checked if what I was saying in the config and still the mp_freemode model still doesn't load

**Comment by smallo92** [comment]
Read it more carefully

**Comment by daMairis** [comment]
Just add custom ped @config.
Then add esx_skin/skinchanger/menu_default from extendedmode github. And make sure to set false line 6 in skinchanger config. And thats it.

**Comment by iglesiiaskeviin** [comment]
thank you very much for the help now if the character loads me, the thing now is that when I enter the data of my skin they are not sent to the database, any ideas?

**Comment by daMairis** [comment]
> thank you very much for the help now if the character loads me, the thing now is that when I enter the data of my skin they are not sent to the database, any ideas?

Show screenshot from users table, please.

**Comment by iglesiiaskeviin** [comment]
https://gyazo.com/4c681385cc27005937e5c8f2e157cab4 here u have.

**Comment by daMairis** [comment]
U missing 5 tables. (firstname, lastname, dateofbirth, sex, height). You must upload esx_identity .sql into users table.

**Comment by iglesiiaskeviin** [comment]
I'm going to try doing that then and now I tell you how

**Comment by iglesiiaskeviin** [comment]
perfect, esx_identity works perfectly but I throw this error in console when creating my character with esx_skin https://gyazo.com/2ca553d9bd39dce2ae33b162852d8f5e , mis cfg está configurado de la siguiente manera:
`
ensure mysql-async
ensure essentialmode
ensure extendedmode
ensure esx_menu_default
ensure esx_menu_list
ensure esx_menu_dialog
ensure skinchanger
ensure esx_identity
ensure esx_skin`

**Comment by daMairis** [comment]
You can try to reinstall:
esx_menu_default
esx_menu_list
esx_menu_dialog
If error does not disappear, its nothing terrible, just ignore.

**Comment by iglesiiaskeviin** [comment]
okay, but the thing is that this error pops up and doesn't send the data to the database

**Comment by daMairis** [comment]
> okay, but the thing is that this error pops up and doesn't send the data to the database
> now appear this error when i try create skin in /skin command: https://gyazo.com/f6f2f124b8070e25fc7a4ab89bb7623c

Show me esx_menu_default manifest file.

**Comment by iglesiiaskeviin** [comment]
https://gyazo.com/ab597314d7cc615019864038894d9081

**Comment by daMairis** [comment]
Try to change depedencies to: extendedmode (remove es_extended and insert extendedmode).
In: menu default, list and dialog, then restart server and check.

**Comment by daMairis** [comment]
Actually in shops, identity too. All es_extended change to extendedmode.

**Comment by iglesiiaskeviin** [comment]
I have done it and still it still does not work, just as quietly, it is normal that it does not work ... this is just a beta.

**Comment by daMairis** [comment]
I just tried to set this up and everything works.
Latest server build for linux/windows.
mysql_async, async, cron, extendedmode, identity, skin, skinchanger, menu default, list and dialog.
Every resource downloaded from extendedmode github.
Seems you are missing something.

**Comment by iglesiiaskeviin** [comment]
Maybe that's if I will check and let you know if it is solved. Thank you for your patience

**Comment by smallo92** [comment]
This whole situation could've been avoided if you joined the discord and read the #faq channel. You need to update your server artifact.

**Comment by iglesiiaskeviin** [comment]
I am already in discord and I literally read everything that was published there, I have tried to install all the essential ESX resources and still the esx_skin still does not work. Yesterday I tried to install the skinchanger and the esx_skin using es_extended and there if the data was entered in the database.

**Comment by daMairis** [comment]
How you downloaded files (skin, skinchanger)?
You just clicked on links in readme file or downloaded as zip from green button?

**Comment by iglesiiaskeviin** [comment]
I used the links that are in the ExM discord
Attached image: https://gyazo.com/a22a734eb7f50dc69389c5cae26111bc

**Comment by daMairis** [comment]
Hmm, can you join server and start playing or you just stuck at skinchanger menu? I can't rly understand problem.

**Comment by iglesiiaskeviin** [comment]
Exactly, I can do everything on the server, the commands work well, there are no errors in the console except for the one that comes out when I give INTRO after choosing the characteristics of my character. Maybe now after trying to migrate my server with es_extended to the new extendedmode to see what happens. 
Before I got the menu of the esx skin locked but I put it to change the dependency to extendedmode and that was solved but the data is still not sent to the ddbb

**Comment by daMairis** [comment]
Give discord nickname and id, we can't spam here so much.

**Comment by iglesiiaskeviin** [comment]
Developerkevin #2383

**Comment by smallo92** [comment]
> I am already in discord and I literally read everything that was published there, I have tried to install all the essential ESX resources and still the esx_skin still does not work. Yesterday I tried to install the skinchanger and the esx_skin using es_extended and there if the data was entered in the database.

Legit, you can actually read what I said next time. You have this serious issue of not actually listening and just ranting on and on. `You need to update your server artifact.`

**Comment by smallo92** [comment]
I'm going to guess you don't know what a server artifact is. That's your FXServer. [Windows](https://runtime.fivem.net/artifacts/fivem/build_server_windows/master/) [Linux](https://runtime.fivem.net/artifacts/fivem/build_proot_linux/master/)

**Comment by iglesiiaskeviin** [comment]
Well, I can assure you that I have the latest FXServer artifact on my server.

**Comment by Salto4501** [comment]
J'ai le même problème que @iglesiiaskeviin , Mais je ne comprend pas très bien votre explication pour corriger cet issue ! Possible d'expliquer la procédure pour la correction ? Dsl sa fait longtemps que je n'est pas toucher fivem

**Comment by Salto4501** [comment]
I have the same problem as @iglesiiaskeviin, But I don't quite understand your explanation to correct this issue! Possible to explain the procedure for the correction? Dsl its been a long time since i haven't touched fivem

**Comment by Salto4501** [comment]
I have the last Artifact on my server is not the problem !

**Comment by yagizher** [comment]
**First, install ExM, then install esx_skin, skinchanger and esx_identity. This isn't an issue about ExM.**
