### ISSUE TITLE
After Spawn, no ammo in weapons

### ISSUE THREAD

**Issue by ayyyzen33** [extendedmode/extendedmode#112]
Hey , when i give a weapon with 200 ammos for exemple , it saving to the database but when i spawn i will have no ammo in my gun . I don't have any script that can be related with this issue , thx for the help

**Comment by FBFezz** [comment]
Im the same, cant even give myself the gun again to get ammo either

**Comment by RockySouthpaw** [comment]
How are you giving yourself the weapon/ammo?

**Comment by yagizher** [comment]
No problem occuring in me.

**Comment by sabbo2001** [comment]
Can you list the other scripts you are using please?

**Comment by ayyyzen33** [comment]
only have my clip system and my weaponshop that's all

**Comment by RockySouthpaw** [comment]
My clip system doesn’t help reproduce the issue. My weaponshop doesn’t help reproduce the issue.

**Comment by sabbo2001** [comment]
The weapon system is a bit wonky. We're looking at it. There are other issues too, like /giveweapon not working for other people.

**Comment by sabbo2001** [comment]
Apparently using newest version of disc_ammo fixes this. Try it please.
