### ISSUE TITLE
attachments disapear on drop

### ISSUE THREAD

**Issue by ali-exacute** [extendedmode/extendedmode#115]
so , just tested as much as i can , and found out everytime i drop my weapon on ground , one of its attachments are gone ...

ex: you have a pistol with flashlight , silencer
after dropping it one time , your silencer is gone
after second drop , flashlight is gone aswell

**Comment by sabbo2001** [comment]
This has nothing to do with Extendedmode, we do not have anything handling "per-unique-weapon" stuff yet.

**Comment by yagizher** [comment]
Same happens to me

**Comment by sabbo2001** [comment]
Dropping weapons with attachments, then retrieving them still with those attachments, is not currently supported as far as I know. Keep watching though as that may change.
