### ISSUE TITLE
extendedmode: The database is not initialized, please wait...

### ISSUE THREAD

**Issue by edgardoalvarez100** [extendedmode/extendedmode#116]
I get this error when trying to connect from fivem

![image](https://user-images.githubusercontent.com/446122/83597976-2ec59200-a52e-11ea-8ac9-f354ba8a1751.png)

**Comment by yagizher** [comment]
Have you set mysql-async up?

**Comment by edgardoalvarez100** [comment]
Yes
![image](https://user-images.githubusercontent.com/446122/83640842-53435d80-a572-11ea-9872-ee6117915219.png)

**Comment by x0Z3ro0x** [comment]
Take a look in your console. Chance are you see -

[ExtendedMode] [INFO] Starting up...

But not -

[ExtendedMode] [INFO] ExtendedMode has been initialized

As the installation documents suggest. This means something isn't installed right and thus you are seeing the message you see when trying to connect. I was able to reproduce your error with a fresh install. I'll see if I can find a fix too.

**Comment by x0Z3ro0x** [comment]
Hmm wasn't able to find a workaround. You will just need to just be patient and wait for a developers touch. Something is causing ExM to get hung up and not initialize. But no errors are produced so I am unsure where to even begin trying to help.

**Comment by PatientXero** [comment]
Ensure that all your addons are up to date. Also, make sure that you are not using addons from the ESX-Org repository.

**Comment by x0Z3ro0x** [comment]
There was no addons, it was a clean server and db with nothing more than what is required at installation.

**Comment by edgardoalvarez100** [comment]
I could solve it, I had mariadb installed instead of mysql.

I installed mysql and it was solved

and use the following settings in the connection
set mysql_connection_string "mysql://root:password@localhost/es_extended?charset=utf8mb4"

**Comment by x0Z3ro0x** [comment]
MySQL Async updated 2 days ago and changed their instructions along with the connection string. This may be responsible for the fix? Regardless glad you got it working and nice job. I will load up the build that I was able to replicate your issue on and see if the new changes to mysql async fix the problem so we can document a fix, as I was already using mysql when I replicated your issue.

**Comment by x0Z3ro0x** [comment]
Works fine, it could be the connection string but I doubt it. The only different is it's defining the charset. There has been to many updates between the posting of the issue and now to tell exactly what fixed it. However it is safe to say that if users follow instructions, then it is currently working :)

**Comment by PatientXero** [comment]
MySQL vs MariaDB has nothing to do with it. It came down to setting up the database privileges correctly. I'm running MariaDB 10.3 without any issues.

1. Make sure you run mysql_secure_installation and secure the core databases.
2. Use mysql to create a new user in the following format: CREATE USER 'user'@'localhost' IDENTIFIED BY 'password';
3. Create the es_extended database.
4. Grant privileges to new user: GRANT ALL PRIVILEGES ON 'es_extended' TO 'user'@'localhost';

Your SQL connection string should be something like this: 

set mysql_connection_string "server=localhost;uid=user;password=password;database=es_extended"

That should get you up and running correctly with MariaDB. Do NOT use root!

**Comment by x0Z3ro0x** [comment]
I already had mysql setup when I replicated the issue and haven't changed it since. I also did not change the way I have privileges setup. Something else had to of changed to correct the issue. Still it's fixed now and that's all that matters. Thanks for adding some MariaDB instructions I know a few people who will find that helpful, I shall share it with them.

ExM took down the instructions for setting up or I would suggest you add your instructions there for everyone to take advantage of. You might still be able to I am not sure, here is the link if you can:

https://extendedmode.github.io/Using%20extendedmode/#troubleshooting
