### ISSUE TITLE
SCRIPT ERROR: @extendedmode/client/functions.lua:359: bad argument #3 to 'vec' (number expected got)

### ISSUE THREAD

**Issue by Salto4501** [extendedmode/extendedmode#117]
J'ai cette erreur en ouvrant le serveur et je croit que cela fait en sorte que je doit recréer mon personne a chaque déconnexion ? Merci a vous

**Comment by smallo92** [comment]
I don't speak whatever that is.

**Comment by JnKTechstuff** [comment]
`I got this error when opening the server and I think it means that I have to recreate my person each time I log out? Thank you`

**Comment by smallo92** [comment]
update your server

**Comment by sabbo2001** [comment]
Closing issue, no more information
