### ISSUE TITLE
No Command in game /setjob /car

### ISSUE THREAD

**Issue by Salto4501** [extendedmode/extendedmode#118]
I can't have /setjob and /car in game so he have the command in the script ? 

You have a solution for this works !

**Comment by yagizher** [comment]
You didnt install it correctly. https://extendedmode.github.io/Using%20extendedmode/#standard-installation

**Comment by Salto4501** [comment]
Yeah is good installing ! All command works. Just /car and /setjob dont works :( !

**Comment by sabbo2001** [comment]
Have you used /setgroup to set your player to the admin group?

**Comment by 400CHVRLT** [comment]
Close this problem, the person has not answered for a long time, if you are reading this, do not leave a problem

**Comment by sabbo2001** [comment]
You need to set the user's group.
