### ISSUE TITLE
Needs backward compatibility with SQL

### ISSUE THREAD

**Issue by MrTeaRexx** [extendedmode/extendedmode#120]
its great that extenedmode has been made for future and backward compatibility, but it also needs this done with the SQL. Older mods require essentialmode, while some require es_extended as its SQL DataBase. Majority of people don't know how to edit them and would be nice if extenedmode had this ability to either be listed as essentialmode or es_extended in the SQL Database

**Comment by RockySouthpaw** [comment]
Pretty sure none of the resources actually require the database to be explicitly named “es_extended”. When you import a SQL and it says “use es_extended” then you just remove that part or rename it to your database name. 

Nothing to do at all with extendedmode. The only resources that even call for “es_extended” are from esx org and there is 0 code that’s says “DATABASE MUST BE NAMED THIS!”.

**Comment by PatientXero** [comment]
This is completely false. esx_datastore, esx_society, and esx_shops call for es_extended, though I have changed the line in the .sql files to point to extendedmode. I have looked for references in both client and server lua's for these add-ons, and I am baffled. I am seriously getting tired of battling these compatibility issues.

**Comment by smallo92** [comment]
It's simple, remove the line in those SQL files, we can't fix dozens of external resources that stupidly include a line that isn't even needed. Blame them, not us.
