### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by ghost** [extendedmode/extendedmode#121]
Extended mode stuck on initialization? It doesnt get passed this? I am only using extendedmode without es_extended is that a issue? Or is that correct?

Could you shed me some light please.

**Comment by sabbo2001** [comment]
Don't use es_extended with Extendedmode. If you want, you can use the most recent version  of essentialmode (cloned directly, not releases). Can you show us your server.cfg file so we can see if you're doing anything wrong there?

**Comment by ghost** [comment]
Ah im soooo dum dum lol I installed es_extended too thats why! Opps my mistake. Thanks dude.

**Comment by 400CHVRLT** [comment]
Can you close the issue?

**Comment by ghost** [comment]
Yes  certainly thank you for helping me out. Good work.
