### ISSUE TITLE
Drop Item doesn't Sync properly

### ISSUE THREAD

**Issue by Jonneis** [extendedmode/extendedmode#122]
I notice the drop item doesn't sync for everyone sometimes, for example if you drop some items on the ground and pick it up and then you bring people on the location where you dropped the item, then this person can see "visualy" the items on the ground he can press E to pick it with the animation but he doesnt receive anything is just a visual bug i guess.

p.s: The pick up animation is not visually work for others.

**Comment by RockySouthpaw** [comment]
In regards to the item drop, I think it’s a network issue. Happens on older es_extendeds. (Just experienced this myself.) You need to re drop it and it’ll solve the issue. I don’t think this is an issue with ExM or something they can fix.
