### ISSUE TITLE
Invisible Player

### ISSUE THREAD

**Issue by J1Mii** [extendedmode/extendedmode#125]
Hi! When I connect to my server, I am invisible. I have no error in the console, I follow all the step for the installation, and I have all the requirements. 

I am on a local server with Windows 10 with the latest version of fxserver, extendedmode and mysql-async

Screen of my console: https://gyazo.com/25598db791e256b5c8f02b45b6dd32aa

Screen of In-Game: https://media.discordapp.net/attachments/575145122745024550/722722431273533470/unknown.png?width=1170&height=658

PS: I try to reinstall all the server and that change nothing.

After I connect the console stay the same without any error. 

Thank you!

**Comment by 400CHVRLT** [comment]
Hello, it is normal, you have to install the esx_skin, and then create the character

**Comment by sabbo2001** [comment]
You must install the ExM forks of esx_skin and skinchanger, that should solve your problems.
