### ISSUE TITLE
when new player join server he not save in database and he stack on awaiting scrip and i got error in console

### ISSUE THREAD

**Issue by fucekar** [extendedmode/extendedmode#138]
SCRIPT ERROR: @extendedmode/server/main.lua:102: attempt to index a nil value (field '?')
> ref (@extendedmode/server/main.lua:102)
>  (@mysql-async/mysql-async.js:15916)

**Comment by nathanctech** [comment]
Your MySQL database is likely not set up correctly. Please review the documentation again.
