### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Lukynnnn** [extendedmode/extendedmode#149]
Hello I get this error, and I dont know how can I repair:

[extendedmode] An error happens for query "INSERT INTO users (accounts, identifier, license) VALUES (?, ?, ?) : ["{\"bank\":50000}","steam:1100001176571f2","license:4a5069590692783a77b30248d12ca16c1bf86b6c"]": ER_BAD_FIELD_ERROR: Unknown column 'license' in 'field list'

**Comment by AgenChicken24** [comment]
It says what you should do man read the error it says `ER_BAD_FIELD_ERROR: Unknown column 'license' in 'field list'` which means that you don't have column license in your database delete the table users and insert it again.
