### ISSUE TITLE
Issue with current code

### ISSUE THREAD

**Issue by benzon** [extendedmode/extendedmode#44]
https://github.com/extendedmode/extendedmode/commit/317f49730adc777f1bf19a111fa20827c11b4ac7#r38733611

Did a comment on a section here - there is an issue.

**Comment by jaymo1011** [comment]
I left a reply on your comment but I'll mirror that here for future reference.

>Are you sure this is the case? The spelling seems correct here: https://github.com/extendedmode/extendedmode/blob/7ee44c5dc588eb75bf604e587b65d779e5b77027/client/modules/streaming.lua#L14

>If you're talking about the difference between the `ExM` and `ESX`, that is handled by this code:
https://github.com/extendedmode/extendedmode/blob/7ee44c5dc588eb75bf604e587b65d779e5b77027/client/functions.lua#L23-L39
essentially mirroring all functions from `ESX` in `ExM` except where there is a function with the same name. In that case, the function within the `ExM` table takes precedence but the mirroring only applies when indexing the `ExM` table leaving the `ESX` table untouched, ensuring backwards compatibility with old scripts.

>Hope that helps! 😄

**Comment by benzon** [comment]
Ahh okay.

Actually found a issue now the way ace is done seems wrong since it adds steam:ID it should just do ID not steam: in front seems to mess things up quite bad to be honest.

**Comment by benzon** [comment]
https://github.com/extendedmode/extendedmode/blob/7ee44c5dc588eb75bf604e587b65d779e5b77027/server/classes/player.lua#L18

This part just did a quick test here, string.sub(self.identifier, 6) sorts out the issue and actually works, since steam: is removed from the identifier like it should be.

**Comment by smallo92** [comment]
Thanks for the help, I have pushed a commit to our dev branch to fix this, it'll be added to main. In the future feel free to submit PRs where appropriate, preferably to our dev branch.

**Comment by jaymo1011** [comment]
#45 merged!
