### ISSUE TITLE
StartDBSync

### ISSUE THREAD

**Issue by AFLovett** [extendedmode/extendedmode#54]
Noticed an issues with function StartDBSync, the function stops after 10 cycles i.e 10 saves.

**Comment by JnKTechstuff** [comment]
Not only that but it seems the database gets disconnected somehow. After 10 saves no database calls are happening from Extendedmode

**Comment by nathanctech** [comment]
Any error messages or anything else that can help? The code is really simple and is an infinite loop...

**Comment by JnKTechstuff** [comment]
Nope but I talked to smallo and the best fix is to wait until the 1.1 compat version is out

**Comment by AFLovett** [comment]
No error messages after StartDBSync loop break, only scripts run are the basic fiveM script to get a server running and mysql-async and extendedmode.

**Comment by AFLovett** [comment]
OK have just spent three hours looking at this problem and looking at sql logs don't know if this helps, the problem looks to be the use of MySQL.Async.transaction, the first 10 transactions (queries) go through correctly , the 11th transaction hangs and does not return a completed or failed response breaking the StartDBSync Loop due to no callback response and locks the Database for all other queries.

**Comment by JnKTechstuff** [comment]
There will be a commit that fixes this soon.

**Comment by jaymo1011** [comment]
#57 should have fixed this, please try the latest version

**Comment by benzon** [comment]
Hmm but wont this old method with out the async cause hitches on save all players?

**Comment by smallo92** [comment]
Resolved in latest dev branch commit
