### ISSUE TITLE
Esx_vehicleshop money

### ISSUE THREAD

**Issue by debianlaw** [extendedmode/extendedmode#58]
When you buy a vehicle it "put" you the same amount with a -, like, a vehicle cost 16,000$ and you have 17,000$ it, when you buy It you have -15,000$. Pls, It happens with allí vehicleshop scripts out there and i don't manager yo fix it.

**Comment by debianlaw** [comment]
Ok, i think It because It takes you two times the money, but with all the scripts

**Comment by debianlaw** [comment]
Pls fix it

**Comment by Uragans** [comment]
Its not related with exm you should ask in main thread.....

**Comment by jaymo1011** [comment]
As was said earlier, this is not a problem with ExtendedMode, please go ask the author of "esx_vehicleshop"
