### ISSUE TITLE
Some keys aren't working

### ISSUE THREAD

**Issue by Nitesam** [extendedmode/extendedmode#67]
Hi! i really like this version of es_extended but i'm having some issue while using some keys, for example, if i try to run this code:

`if IsControlJustReleased(0, 167) then 
	ESX.ShowNotification("Hi! I'm Here!")
end` -- 167 = F6

Nothing happens ( same for F5)

but if i do 

`if IsControlJustReleased(0, 288) then 
	ESX.ShowNotification("Hi! I'm Here!")
end` -- 288= F1

Everything works! I don't know what the problem is, but i'm getting this error only with this version of esx Framework.

Thank you in advance!

**Comment by jaymo1011** [comment]
That is a **very** odd issue as the condition in those statements is actually part of GTA not FiveM nor ExM...

Perhaps you have another resource installed that is disabling those controls or the game is disabling them for some reason? Try `IsDisabledControlJustReleased(0, 167)` and see if that works. If so then there is  *something* disabling those controls but as far as I am aware, ExM does not disable any controls.

**Comment by Nitesam** [comment]
Yeah i was checking ExM right now and as you said nothing is disabling those controls, anyway, thank you for your reply!
