### ISSUE TITLE
Database issue

### ISSUE THREAD

**Issue by heyheyitsmeman** [extendedmode/extendedmode#68]
While helping a person with the installation of extendedmode, I noticed that, If you are planning on using esplugin_mysql, you will go and upload their SQL file, which creates a ```users``` table. Then, you come here to install extendedmode, you try to upload the SQL file, which ALSO tries to create a ```users``` table. And you get this "Table `users` already exists". Maybe take a look, compare them and find a workaround?

**Comment by smallo92** [comment]
You don't use esplugin_mysql with extendedmode.

**Comment by heyheyitsmeman** [comment]
OH! Alright, didn't know that. My bad, veery sorry!
