### ISSUE TITLE
Some TriggerServerCallback errors

### ISSUE THREAD

**Issue by chopo156** [extendedmode/extendedmode#69]
i update all the esx resources but keep facing some problems with esx_service and esx_society.
The _service error appeard when i try to change cloth in esx_firejob, and _society society error appeard when im the boss in the job [https://image.prntscr.com/image/GWh37ovURrKtY1ukFucWhw.png](url)
[https://image.prntscr.com/image/ekweL-tBTTWUrTaOfUnGNw.png](url)

**Comment by RockySouthpaw** [comment]
Does this occur with esx_policejob (current version)

**Comment by smallo92** [comment]
Update your server artifact
