### ISSUE TITLE
esx_datastore

### ISSUE THREAD

**Issue by LySoon** [extendedmode/extendedmode#75]
![image](https://user-images.githubusercontent.com/49767982/82143447-af0ca780-984c-11ea-8787-9cfcb411e9b0.png)

gives this error when i buy new clothes, also gives the same error with latest esx_clothestore.

didn't started the esx_property ? might because of this maybe?

**Comment by smallo92** [comment]
update esx_datastore

**Comment by benzon** [comment]
Datastore is one of the worst ESX Resources in history very poor optimization.

**Comment by Lalutoww** [comment]
I also have this error. I'm using the latest esx_datastore.
