### ISSUE TITLE
Ammo consumption

### ISSUE THREAD

**Issue by zek0** [extendedmode/extendedmode#81]
Example: We have 2 pistols in inventory "weapon_pistol" and "weapon_combatpistol" with 10 ammo on it. We start shooting and ammo start consuming from both weapons.
Also in database loadout save correctly, but after relogin weapons has wrong ammo count.

**Comment by benzon** [comment]
That is a GTA V thing, not a extendedmode thing, the issues if you got weapons, that share same ammo type.

It will be consumed for both of them, thats the nature of GTA V
