### ISSUE TITLE
SCRIPT ERROR attempt to perform arithmetic on a nil value (field 'money')

### ISSUE THREAD

**Issue by Leon485** [extendedmode/extendedmode#84]
I`m using both essentialmode and extendedmode on my server and whenever i buy something i get this error. Do you have any clue on what could be causing this?

![Capture3](https://user-images.githubusercontent.com/63073120/82454698-fc398500-9aa9-11ea-960a-e8146055fb48.PNG)

And it`s not just policejob, whenever you buy something this happens, ive also removed essentialmode and this hasnt solved the problem

**Comment by smallo92** [comment]
update essentialmode

**Comment by Leon485** [comment]
It was es_plugin
