### ISSUE TITLE
Undefined items

### ISSUE THREAD

**Issue by Leon485** [extendedmode/extendedmode#85]
![image](https://user-images.githubusercontent.com/63073120/82459499-ef1f9480-9aaf-11ea-9848-9b53ed1849e3.png)

 in the bottom right it shows that the gun is false defined when it it thrown and picked up. how would i go about fixing this?

**Comment by christerjohansson** [comment]
You might want to add that particular item to your database under items, or if you have weapon shops, in weashops table. If they are already in there, try searching that message in the scripts to find out where it looks for information about items.

**Comment by Leon485** [comment]
@christerjohansson i do have it in my weashop and items but this is for every single item in the game
