### ISSUE TITLE
Cant Join Server; extendedmode is still initalizing database, please wait

### ISSUE THREAD

**Issue by CrazedslawDev** [extendedmode/extendedmode#89]
i keep getting this error when running my server

server config:

# Only change the IP if you're using a server with multiple network interfaces, otherwise change the port only.
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

add_principal group.admin group.user
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow

set mysql_connection_string "server=localhost;uid=root;password=####;database=ESXserver;ssl=none"
set es_enableCustomData 1

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure fivem
ensure hardcap
ensure rconlog
ensure scoreboard

# ESSENTIALS
ensure essentialmode
ensure mysql-async
ensure fxmigrant
ensure es_admin2
ensure esplugin_mysql
ensure extendedmode
ensure async

ensure esx_menu_default
ensure esx_menu_list
ensure esx_menu_dialog

# CAR ADDONS
ensure evo3
ensure Agera
ensure akina
ensure na6
ensure vMenu
ensure fd
ensure lanos3
ensure dc5
ensure jza80
ensure vulcan
ensure r35
ensure mr2sw20
ensure mr2zzw30
ensure honcrx91
ensure 350z
ensure 68mustang
ensure 180sx
ensure 370z
ensure ae86
ensure ap2
ensure celisupra
ensure cp9a
ensure eg6
ensure zievs
ensure er34
ensure evo9
ensure fc3s
ensure fk2
ensure fk8
ensure fto
ensure jza70
ensure kgc10
ensure mazdamx5
ensure na1
ensure nr30rsx
ensure nsx4
ensure onevia
ensure r31
ensure r32
ensure r33
ensure rx811
ensure s13
ensure s15
ensure sil80
ensure silvia3
ensure skylinec110
ensure sti
ensure SubaruGTv2
ensure Z31
ensure z32
ensure 1970charger
ensure celgt4
ensure civic
ensure eclipse
ensure firebird
ensure gt86
ensure maj86
ensure supraa90
ensure toyotaprius

# GUN ADDONS
ensure M16

# This allows players to use scripthook-based plugins such as the legacy Lambda Menu.
# Set this to 1 to allow scripthook. Do note that this does _not_ guarantee players won't be able to use external plugins.
sv_scriptHookAllowed 1

# Uncomment this and set a password to enable RCON. Make sure to change the password - it should look like rcon_password "YOURPASSWORD"
#rcon_password ""

# A comma-separated list of tags for your server.
# For example:
# - sets tags "drifting, cars, racing"
# Or:
# - sets tags "roleplay, military, tanks"
sets tags "default"

# A valid locale identifier for your server's primary language.
# For example "en-US", "fr-CA", "nl-NL", "de-DE", "en-GB", "pt-BR"
sets locale "root-AQ" 
# please DO replace root-AQ on the line ABOVE with a real language! :)

# Set an optional server info and connecting banner image url.
# Size doesn't matter, any banner sized image will be fine.
#sets banner_detail "https://url.to/image.png"
#sets banner_connecting "https://url.to/image.png"

# Set your server's hostname
sv_hostname "Crazedslaw's Test Server"

# Nested configs!
#exec server_internal.cfg

# Loading a server icon (96x96 PNG file)
#load_server_icon myLogo.png

# convars which can be used in scripts
set temp_convar "hey world!"

# Uncomment this line if you do not want your server to be listed in the server browser.
# Do not edit it if you *do* want your server listed.
#sv_master1 ""

# Add system admins
add_ace group.admin command allow # allow all commands
add_ace group.admin command.quit deny # but don't allow quit
add_principal identifier.fivem:1 group.admin # add the admin to the group

# Hide player endpoints in external log output.
sv_endpointprivacy true

# enable OneSync with default configuration (required for server-side state awareness)
onesync_enabled true

# Server player slot limit (must be between 1 and 32, unless using OneSync)
sv_maxclients 5

# Steam Web API key, if you want to use Steam authentication (https://steamcommunity.com/dev/apikey)
# -> replace "" with the key
set steam_webApiKey "####################"

# License key for your server (https://keymaster.fivem.net)
sv_licenseKey ##################

**Comment by smallo92** [comment]
disable `esplugin_mysql` and change 
```lua
add_ace resource.es_extended command.add_ace allow
add_ace resource.es_extended command.add_principal allow
add_ace resource.es_extended command.remove_principal allow
add_ace resource.es_extended command.stop allow
```
all those to say `extendedmode`, not `es_extended`

**Comment by CrazedslawDev** [comment]
> disable `esplugin_mysql` and change
> 
> ```lua
> add_ace resource.es_extended command.add_ace allow
> add_ace resource.es_extended command.add_principal allow
> add_ace resource.es_extended command.remove_principal allow
> add_ace resource.es_extended command.stop allow
> ```
> 
> all those to say `extendedmode`, not `es_extended`

still getting the exact same error. I should also mention there are no errors or anything along those lines in my server console

**Comment by smallo92** [comment]
Go through and update all your resources, essentialmode, mysql-async. Also update the server artifact itself. and double check installation guides to make sure you're loading things in the correct order.

**Comment by CrazedslawDev** [comment]
> Go through and update all your resources, essentialmode, mysql-async. Also update the server artifact itself. and double check installation guides to make sure you're loading things in the correct order.

All files were only downloaded 2 hours ago and ive checked and the load order is definitely correct

**Comment by smallo92** [comment]
show me what your server console says once it's loaded

**Comment by CrazedslawDev** [comment]
here it is
![console](https://user-images.githubusercontent.com/65857370/82756858-a24ffc80-9dd4-11ea-9edb-4538bfbbbb07.PNG)

**Comment by smallo92** [comment]
well I can tell there essentialmode isn't updated, since it's on 6.4.2 and also extendedmode hasn't started correctly. Show me what it says a little higher up. For essentialmode download the github repository, not the releases.

**Comment by CrazedslawDev** [comment]
It doesnt have an error and just says its started 
![console2](https://user-images.githubusercontent.com/65857370/82756966-55b8f100-9dd5-11ea-8793-5c9c3a37face.PNG)

**Comment by smallo92** [comment]
start async before mysql-async, but other then that I actually have no idea, it kind of seems like it's not able to connect to your database

**Comment by CrazedslawDev** [comment]
the database is running on localhost since its a homehosted server. could it be the sql databases port or the fact the IP is on 127.0.0.1 instead of my servers public IP

**Comment by CrazedslawDev** [comment]
> start async before mysql-async, but other then that I actually have no idea, it kind of seems like it's not able to connect to your database

Ok so i checked my HeidiSQL and it only has successful connects so its connecting but its not initializing in game
![sqlman](https://user-images.githubusercontent.com/65857370/82768861-77dc5e80-9e29-11ea-8335-489134b20358.PNG)

**Comment by CLEMARCx** [comment]
Hi,
remove the ssl=none flag and then you get an error.
I use mariadb instead of the normal mysql now and it is working
