### ISSUE TITLE
Hear players from across map

### ISSUE THREAD

**Issue by Leon485** [extendedmode/extendedmode#90]
When using ExM i can hear players from across the map with everything set up correctly. When using es_extended this doesnt happen however i really want to use ExM as it is much better. Is there anything which can be done about this?

**Comment by smallo92** [comment]
voice chat has nothing to do with esx or extendedmode, it's whatever voice chat resource you're using.

**Comment by Leon485** [comment]
im using esx_voice and ive tried it on both ExM and es_extended

**Comment by smallo92** [comment]
update esx_voice and are there any errors?

**Comment by Leon485** [comment]
There are no errors and im using the latest esx_voice
