### ISSUE TITLE
Inventroy Items, Bank, Cash, Weapons and parts of Hud are gone

### ISSUE THREAD

**Issue by HirohitoDE** [extendedmode/extendedmode#91]
Hey, so I installed extendedmode today and had the problem mentioned in #89. I fixed it by doing what @smallo92 recommended. Unfortunately the Inventory, the Bank-account and the cash is gone/empty except für 50k startmoney. Also, all parts of my hud are gone except for the society-bank-account.
I hope someone has an idea whats wrong.
Cheers

My Server.cfg
start mumble-voip
start rp-radio
setr voice_use3dAudio true
setr voice_useSendingRangeOnly true

# Standartskripte
start mapmanager
start chat
start spawnmanager
start sessionmanager
start fivem
start hardcap
start webadmin-lua
start wap-settings
start wap-chatlog
start fivem-ipl
start PvP
start EasyAdmin
add_ace group.admin easyadmin allow
set ea_minIdentifierMatches 2
start start async
start mysql-async
start essentialmode
start extendedmode
#start esplugin_mysql
start es_admin2
start es_ui
add_ace resource.extendedmode command.add_ace allow
add_ace resource.extendedmode command.add_principal allow
add_ace resource.extendedmode command.remove_principal allow
add_ace resource.extendedmode command.stop allow
start load
start esx_discord_bot
start DiscordBot
start progressBars

## Esx Basis ##
start cron
start es_extended
start esx_society
start instance
start es_camera
start skinchanger
start esx_addonaccount
start esx_addoninventory
start esx_accessories
start status
start NativeUI
start RageUI
start ELS-FiveM

# gcphone

start gcphone
start esx_addons_gcphone

# ESX Skripte
start vehicle-control
start esx_doorlock
start esx_ambulancejob
start esx_animations
start new_banking
#start esx_bankerjob
start esx_barbershop
start esx_basicneeds
start esx_billing
#start esx_boat
start esx_boilerplate
start esx_clotheshop
start esx_cruisecontrol
start esx_datastore
start esx_dmvschool
start esx_garage
start esx_holdup
start esx_identity
start esx_joblisting
start esx_jobs
start esx_license
start esx_lscustom
start esx_mechanicjob
start esx_menu_default
start esx_menu_dialog
start esx_menu_list
start esx_migrate
start esx_optionalneeds
start esx_property
start esx_realestateagentjob
#start esx_rpchat
start esx_service
start 99kr-shops
start gvrp_waffenshop
start esx_shops
start esx_sit
start esx_skin
start esx_status
start esx_taxijob
start esx_vehicleshop
start esx_policejob
#start esx_voice
start esx_weaponshop
#start esx_drp_garage
start esx_advancedgarage
start esx-kr-vehicle-push
start fivem-seatbelt
#start esx_scoreboard
start esx_zaidejumeniu
start LegacyFuel
start trew_hud_ui
start esx_vangelico_robbery
start esx_drugs_custom
start Teleport
start esx_blackmoney
start rp-radio
start esx_pizza
start esx_truckerjob
start esx_garbagejob
start esx_AdvancedFishing
start esx_drugselling
start trafficadjuster
start esx-qalle-sellvehicles
start esx_extraitems
start esx_tattooshop
start es_carwash
start esx_trunk
start ambulance-mission
start esx_farmoranges
start jsfour-criminalrecord

## End of ESX Pack ##

#Divers 

start rconlog
ensure krz_personalmenu
start PoliceVehiclesWeaponDeleter
start VehicleAirControl
start RealisticVehicleFailure
start disabledispatch
start CarRental
start handsup
start ReducedNPCs
start No-NPC
start Jailer
start jsfour-idcard
start modelblacklist
start gvrp_nodrops
start pNotify
start gvrp_locknpc
start dpemotes
start DiscordPresence
start VehicleExtraMenu
start flashbang
start carremote
start HeliCam-FiveM
start esx_cigarette
start esx_handcuffs
start StreetRaces
start InteractSoundS
start CuffedUp
start esx_borrmaskin
start esx_robatm
start plateRemover
start mhacking
start esx_knatusblowtorch
start esx_knatusrobberybank
start gvrp_tracking
start mark-b_police-tracker
start kozeuh-megaphone
start gvrp_waffenraub
start JF_SeatShuffle
start esx_ktackle
start esx_extraitems
start simpletp
start esx_extraitems

**Comment by smallo92** [comment]
You need to migrate the accounts. Run `migratedb` in the server console. Make sure you backup your database like it asks.

**Comment by smallo92** [comment]
Also join our discord for support instead of making issues here https://discord.gg/kcEwdy3

**Comment by HirohitoDE** [comment]
Okay I'll ask on the discord since it's not working unfortunately.

**Comment by PaulyJ1** [comment]
Looking at your server.cfg. You have start essentialmode, start extendedmode AND start es_extended. Why? 

Also, your startup is pretty messed up.

**Comment by HirohitoDE** [comment]
Yeah I know its pretty messy atm. I fixed the extendedmode issue tho. Ty anyways
