### ISSUE TITLE
user_inventory

### ISSUE THREAD

**Issue by FBFezz** [extendedmode/extendedmode#92]
Im not sure what script i need for user_inventory but I'm using latest version of extendedmode but getting this error in Rcon

![image](https://user-images.githubusercontent.com/43589668/82779153-54c2a680-9e4b-11ea-9c19-d8a09d87d3c6.png)

**Comment by smallo92** [comment]
That's a warning not an error. You seem to have a slow connection between your database and the sever, nothing we can do about that.

**Comment by FBFezz** [comment]
Ah my bad, whats the bit about the user accounts and user inventory tho? Am i supposed to have them in my db?

**Comment by smallo92** [comment]
Yes, did you not migrate your database? In server console try running `migratedb` and make sure you read the information it provides you CAREFULLY

**Comment by FBFezz** [comment]
Ok did that and got an error but not sure if its because of the hitch warnings (Sorry for this, haven't slept much and i appreciate the help)

![image](https://user-images.githubusercontent.com/43589668/82779992-9b190500-9e4d-11ea-8d9d-be59acca05c5.png)

**Comment by smallo92** [comment]
wait it's a fresh server? Did you not import `extendedmode.sql` into your database?

**Comment by smallo92** [comment]
Read this carefully https://extendedmode.github.io/Using%20extendedmode/#standard-installation

**Comment by FBFezz** [comment]
Ah thank you, sorry for this Ill do it now and close this, if i have any more issues ill re-open this.
